version: '3.1'

volumes:
  node_modules:
services:
  web:
    build: .
    ports:
     - "80:80"
     - "3000:3000"
    environment:
      PORT: 80
      REACT_APP_PORT: 3000
      NODE_ENV: production
      DB_HOSTNAME: db
      DB_DIALECT: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
     - .:/app:z
     - node_modules:/app/node_modules:Z
    links:
     - db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
